name: stage

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ENVIRONMENT: stage
      ACTIONS_STEP_DEBUG: false
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
      STAGE_RDS_PASS: ${{ secrets.STAGE_RDS_PASS }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11
      - name: removing terraform wrapper
        run: mv ${TERRAFORM_CLI_PATH}/terraform-bin ${TERRAFORM_CLI_PATH}/terraform || true

      - name: terraform deploy
        run: |
          export TF_VAR_pg_password=${STAGE_RDS_PASS}
          cd ${GITHUB_WORKSPACE}/${ENVIRONMENT}
          terraform init
          terraform plan -compact-warnings
          terraform apply -auto-approve
